// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsdwydqxlyknnhjanpir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZHd5ZHF4bHlrbm5oamFucGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTcwODIsImV4cCI6MjA2NTc5MzA4Mn0.eXWyZ7eyaBSve4XAGHpKeh_bwR3vfU4I1it417lmeaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);